var path = require('path');

module.exports = {
    '@assets': path.resolve(__dirname, "./src/assets"),
    '@colorpicker': path.resolve(__dirname, "./src/colorpicker"),
    '@commands': path.resolve(__dirname, "./src/commands"),
    '@core': path.resolve(__dirname, "./src/core"),
    '@csseditor': path.resolve(__dirname, "./src/csseditor"),
    '@exporter': path.resolve(__dirname, "./src/exporter"),
    '@i18n': path.resolve(__dirname, "./src/i18n"),
    '@icon': path.resolve(__dirname, "./src/icon"),
    '@image-resource': path.resolve(__dirname, "./src/image-resource"),
    '@interpolate': path.resolve(__dirname, "./src/interpolate"),
    '@items': path.resolve(__dirname, "./src/items"),
    '@renderer': path.resolve(__dirname, "./src/renderer"),
    '@manager': path.resolve(__dirname, "./src/manager"),
    '@parser': path.resolve(__dirname, "./src/parser"),
    '@preset': path.resolve(__dirname, "./src/preset"),
    '@property-parser': path.resolve(__dirname, "./src/property-parser"),
    '@shortcuts': path.resolve(__dirname, "./src/shortcuts"),
    '@types': path.resolve(__dirname, "./src/types"),
    '@ui': path.resolve(__dirname, "./src/ui"),
    '@unit': path.resolve(__dirname, "./src/unit"),
    '@util': path.resolve(__dirname, "./src/util"),
}