/* event trigger */
export const CHANGE_STRORAGE = 'CHANGE_STORAGE'
export const CHANGE_TOOL = 'CHANGE_TOOL'
export const CHANGE_TOOL_SIZE = 'CHANGE_TOOL_SIZE'
export const CHANGE_HISTORY = 'CHANGE_HISTORY'


export const CHANGE_TIMELINE = 'CHANGE_TIMELINE'
export const CHANGE_SELECTION = 'CHANGE_SELECTION'
export const CHANGE_KEYFRAME = 'CHANGE_KEYFRAME'
export const CHANGE_KEYFRAME_SELECTION = 'CHANGE_KEYFRAME_SELECTION'

export const CHANGE_EDITOR = 'CHANGE_EDITOR'
export const CHANGE_INSPECTOR = 'CHANGE_INSPECTOR'
export const COPY_ITEMS = 'COPY_ITEMS'
export const CHANGE_PROJECT = 'CHANGE_PROJECT'
export const CHANGE_ARTBOARD = 'CHANGE_ARTBOARD'
export const CHANGE_DIRECTORY = 'CHANGE_DIRECTORY'
export const CHANGE_LAYER = 'CHANGE_LAYER'
export const CHANGE_RECT = 'CHANGE_RECT' 
export const CHANGE_IMAGE = 'CHANGE_IMAGE'
export const CHANGE_BACKGROUND_IMAGE = 'CHANGE_BACKGROUND_IMAGE'
export const CHANGE_BORDER_IMAGE = 'CHANGE_BORDER_IMAGE'
export const CHANGE_MASK_IMAGE = 'CHANGE_MASK_IMAGE'
export const CHANGE_BOX_IMAGE = 'CHANGE_BOX_IMAGE'
export const CHANGE_BOXSHADOW = 'CHANGE_BOXSHADOW'
export const CHANGE_TEXTSHADOW = 'CHANGE_TEXTSHADOW'
export const CHANGE_COLORSTEP = 'CHANGE_COLORSTEP'

export const ADD_TIMELINE = 'ADD_TIMELINE'
export const ADD_KEYFRAME = 'ADD_KEYFRAME'

export const SELECT_TAB_LAYER = 'SELECT_TAB_LAYER'
export const SELECT_TAB_IMAGE = 'SELECT_TAB_IMAGE'

export const CHANGE_SVG_LIST = 'CHANGE_SVG_LIST'