
export const ITEM_MOVE_TO = 'item/move/to'
export const ITEM_MOVE_NEXT = 'item/move/next'
export const ITEM_MOVE_LAST = 'item/move/last'
export const ITEM_MOVE_FIRST = 'item/move/first'
export const ITEM_MOVE_IN = 'item/move/in'
export const ITEM_MOVE_IN_LAYER = 'item/move/in/layer'
export const ITEM_MOVE_PREV = 'item/move/prev'
export const ITEM_ADD_INDEX = 'item/add/index'
export const ITEM_NEXT_INDEX = 'item/next/index'
export const ITEM_PREV_INDEX = 'item/prev/index'
export const ITEM_MOVE_X = 'item/move/x'
export const ITEM_MOVE_Y = 'item/move/y'