
export const STORAGE_GET = 'storage/get'
export const STORAGE_SET = 'storage/set'
export const STORAGE_PAGES = 'storage/pages'
export const STORAGE_LAYERS = 'storage/layers'
export const STORAGE_IMAGES = 'storage/images'
export const STORAGE_UNSHIFT_LAYER = 'storage/unshift/layer'

export const STORAGE_REMOVE_LAYER = 'storage/remove/layer'
export const STORAGE_REMOVE_PAGE = 'storage/remove/page'
export const STORAGE_UNSHIFT_PAGE = 'storage/unshift/page'
export const STORAGE_ADD_PAGE = 'storage/add/page'
export const STORAGE_ADD_LAYER = 'storage/add/layer'
export const STORAGE_ADD_IMAGE = 'storage/add/image'
export const STORAGE_DELETE_PAGE = 'storage/delete/page'
export const STORAGE_DELETE_IMAGE = 'storage/delete/image'
export const STORAGE_SAVE = 'storage/save'
export const STORAGE_SAVE_LAYER = 'storage/save/layer'
export const STORAGE_SAVE_PAGE = 'storage/save/page'
export const STORAGE_SAVE_IMAGE = 'storage/save/image'
export const STORAGE_LOAD_LAYER = 'storage/load/layer'
export const STORAGE_LOAD_PAGE = 'storage/load/page'
export const STORAGE_LOAD_IMAGE = 'storage/load/image'
export const STORAGE_LOAD = 'storage/load'