export const TIMELINE_GET = 'timeline/get';
export const TIMELINE_PUSH = 'timeline/push';
export const TIMELINE_LIST = 'timeline/list';
export const TIMELINE_SEEK = 'timeline/seek';
export const TIMELINE_NOT_EXISTS = 'timeline/not/exists'
export const TIMELINE_NOT_EXISTS_KEYFRAME = 'timeline/not/exists/keyframe'
export const TIMELINE_MIN_TIME_IN_KEYFRAMES = 'timeline/min/time/in/keyframes'
export const TIMELINE_MAX_TIME_IN_KEYFRAMES = 'timeline/max/time/in/keyframes'
export const TIMELINE_MAX_SECOND = 300;
export const TIMELINE_1_SECOND_WIDTH = 100;
export const TIMELINE_TOTAL_WIDTH = TIMELINE_1_SECOND_WIDTH * TIMELINE_MAX_SECOND;